### ISSUE TITLE
Český svět - problém se 3 čísly

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#112]
U těchto 3 čísel [Českého světa](http://kramerius.mzk.cz/search/handle/uuid:9ee4d9f0-6a7a-11e4-9d98-005056825209) selhává proces pro změnu viditelnosti/reindexace:

ročník 1906-1907, číslo 25:
uuid:234699c0-727f-11e4-85f4-5ef3fc9ae867

ročník 1926-1927, číslo: 23
uuid:92a00610-9a8b-11e4-a2db-005056825209

ročník 1926-1927, číslo: 23
uuid:95b0e1d0-9a86-11e4-a2db-005056825209

Jun 05, 2016 7:22:38 PM cz.incad.kramerius.impl.FedoraAccessImpl processSubtree
WARNING: could not read root RELS-EXT, skipping object  (uuid:234699c0-727f-11e4-85f4-5ef3fc9ae867):java.io.FileNotFoundException: http://195.113.155.102:7580/fedora/get/uuid:234699c0-727f-11e4-85f4-5ef3fc9ae867/RELS-EXT
Jun 05, 2016 7:22:40 PM cz.incad.kramerius.service.impl.PolicyServiceImpl setPolicy
WARNING: Cannot set policy for object uuid:234699c0-727f-11e4-85f4-5ef3fc9ae867, skipping: javax.xml.ws.soap.SOAPFaultException:  Caused by: no path in db registry for [uuid:234699c0-727f-11e4-85f4-5ef3fc9ae867]
Jun 05, 2016 7:22:41 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: system error file contains errors
cz.incad.kramerius.processes.WarningException: system error file contains errors
    at cz.incad.kramerius.processes.impl.ProcessStarter.checkErrorFile(ProcessStarter.java:185)
    at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:127)

Přes indexaci dokumentů uuid ani nejsou dohledatelná.

**Comment by LenkaKravecova** [comment]
Celá čísla nejsou ve Fedoře. Požadavek na LTP.

**Comment by LenkaKravecova** [comment]
Reimport z LTP i změna viditelnosti provedena úspěšně,
