### ISSUE TITLE
Ve Fedoře častý error message

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#126]
Na dk-back.infra.mzk.cz:
docker logs --tail=30 -f 381_fcrepo_1

častá chybová hláška

```
ERROR 2016-09-08 12:56:02.005 [http-nio-8080-exec-1324] (FedoraAccessServlet) Object or datastream not found for request: http://fedora.dk-back.infra.mzk.cz/fedora/get/vc:ef1769f6-c97c-4c24-a547-b4b2055148e4/DC (actionLabel=Access)
org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: no path in db registry for [vc:ef1769f6-c97c-4c24-a547-b4b2055148e4]
    at org.fcrepo.server.storage.lowlevel.DBPathRegistry.get(DBPathRegistry.java:147) ~[fcrepo-server-3.8.1.jar:na]
    at org.fcrepo.server.storage.lowlevel.defaultstore.Store.getFile(Store.java:177) ~[fcrepo-server-3.8.1.jar:na]
    at org.fcrepo.server.storage.lowlevel.defaultstore.Store.retrieve(Store.java:144) ~[fcrepo-server-3.8.1.jar:na]
    at org.fcrepo.server.storage.lowlevel.DefaultLowlevelStorage.retrieveObject(DefaultLowlevelStorage.java:87) ~[fcrepo-server-3.8.1.jar:na]
    at org.fcrepo.server.storage.lowlevel.DefaultLowlevelStorageModule.retrieveObject(DefaultLowlevelStorageModule.java:133) ~[fcrepo-server-3.8.1.jar:na]
    at org.fcrepo.server.storage.DefaultDOManager.getReader(DefaultDOManager.java:733) ~[fcrepo-server-3.8.1.jar:na]
    at org.fcrepo.server.access.DefaultAccess.getDatastreamDissemination(DefaultAccess.java:1109) ~[fcrepo-server-3.8.1.jar:na]
    at org.fcrepo.server.access.FedoraAccessServlet.getDatastreamDissemination(FedoraAccessServlet.java:593) ~[fcrepo-server-3.8.1.jar:na]
    at org.fcrepo.server.access.FedoraAccessServlet.doGet(FedoraAccessServlet.java:445) ~[fcrepo-server-3.8.1.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) [servlet-api.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [catalina.jar:8.5.4]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.4]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.4]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.4]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.4]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:369) [spring-security-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.fcrepo.server.security.jaas.AuthFilterJAAS.doFilter(AuthFilterJAAS.java:329) [fcrepo-security-jaas-3.8.1.jar:na]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:381) [spring-security-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:109) [spring-security-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:381) [spring-security-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:168) [spring-security-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.4]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.4]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.4]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [catalina.jar:8.5.4]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522) [catalina.jar:8.5.4]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.4]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.5.4]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) [catalina.jar:8.5.4]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.4]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [catalina.jar:8.5.4]
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110) [tomcat-coyote.jar:8.5.4]
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.4]
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785) [tomcat-coyote.jar:8.5.4]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425) [tomcat-coyote.jar:8.5.4]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.4]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.4]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

**Comment by leiblix** [comment]
Pravděpodobně to bud taky důvod proč je v Krameriu často zalogováno toto:

```
kramerius_1  | 11-Oct-2016 12:35:56.887 WARNING [http-nio-8080-exec-33] cz.incad.kramerius.virtualcollections.VirtualCollectionsManager.doVC Could not get virtual collection for  vc:52e9443b-2510-4ebc-a7a4-8104378e4bae: cz.incad.kramerius.FedoraIOException
kramerius_1  | 11-Oct-2016 12:35:56.933 WARNING [http-nio-8080-exec-33] cz.incad.kramerius.virtualcollections.VirtualCollectionsManager.doVC Could not get virtual collection for  vc:6b45fd6b-3bbd-4eaf-83fe-2c673497970b: java.io.FileNotFoundException: http://fedora.dk-back.infra.mzk.cz/fedora/get/vc:6b45fd6b-3bbd-4eaf-83fe-2c673497970b/DC
kramerius_1  | 11-Oct-2016 12:35:57.009 WARNING [http-nio-8080-exec-33] cz.incad.kramerius.virtualcollections.VirtualCollectionsManager.doVC Could not get virtual collection for  vc:9784fefa-4ba8-4d6d-a4fc-85174d12aa23: java.io.FileNotFoundException: http://fedora.dk-back.infra.mzk.cz/fedora/get/vc:9784fefa-4ba8-4d6d-a4fc-85174d12aa23/DC
kramerius_1  | 11-Oct-2016 12:35:57.025 WARNING [http-nio-8080-exec-33] cz.incad.kramerius.virtualcollections.VirtualCollectionsManager.doVC Could not get virtual collection for  vc:98859247-7400-4f29-9312-45cb24e56723: cz.incad.kramerius.FedoraIOException
kramerius_1  | 11-Oct-2016 12:35:57.103 WARNING [http-nio-8080-exec-33] cz.incad.kramerius.virtualcollections.VirtualCollectionsManager.doVC Could not get virtual collection for  vc:d3f011e3-f1fd-4025-a907-68a860460841: java.io.FileNotFoundException: http://fedora.dk-back.infra.mzk.cz/fedora/get/vc:d3f011e3-f1fd-4025-a907-68a860460841/DC
kramerius_1  | 11-Oct-2016 12:35:57.174 WARNING [http-nio-8080-exec-33] cz.incad.kramerius.virtualcollections.VirtualCollectionsManager.doVC Could not get virtual collection for  vc:ef1769f6-c97c-4c24-a547-b4b2055148e4: java.io.FileNotFoundException: http://fedora.dk-back.infra.mzk.cz/fedora/get/vc:ef1769f6-c97c-4c24-a547-b4b2055148e4/DC
```

**Comment by Jenyk** [comment]
Odkazy na neexistující VC jsou odstraněny z objektů ve fedoře, objekty reindexovány, solr optimalizován (to bylo potřeba k odstranění starých VC z http://solr.dk-back.infra.mzk.cz/solr/terms?terms=true&terms.fl=collection&terms.limit=1000)
