### ISSUE TITLE
SOLR dlouhé dotazy

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#141]
SOLR pořád dělá problémy, navíc se v logu objevuje chyba:

vypadá to, že něco položilo dlouhý dotaz do SOLRu, ale k odpovědi už nedošlo (connection timeout kvůli reverzní proxy)

```
solr_1  | 11-Oct-2016 17:01:08.322 SEVERE [http-apr-8080-exec-183] org.apache.solr.common.SolrException.log org.apache.catalina.connector.ClientAbortException: java.io.IOException: APR error: -32
solr_1  |   at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:396)
solr_1  |   at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:426)
solr_1  |   at org.apache.tomcat.util.buf.ByteChunk.append(ByteChunk.java:339)
solr_1  |   at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:421)
solr_1  |   at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:409)
solr_1  |   at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:97)
solr_1  |   at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
solr_1  |   at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
solr_1  |   at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
solr_1  |   at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
solr_1  |   at org.apache.solr.common.util.FastWriter.flush(FastWriter.java:113)
solr_1  |   at org.apache.solr.servlet.SolrDispatchFilter.writeResponse(SolrDispatchFilter.java:344)
solr_1  |   at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:265)
solr_1  |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
solr_1  |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
solr_1  |   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
solr_1  |   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
solr_1  |   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
solr_1  |   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
solr_1  |   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
solr_1  |   at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
solr_1  |   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
solr_1  |   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
solr_1  |   at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
solr_1  |   at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
solr_1  |   at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2445)
solr_1  |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
solr_1  |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
solr_1  |   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
solr_1  |   at java.lang.Thread.run(Thread.java:745)
solr_1  | Caused by: java.io.IOException: APR error: -32
solr_1  |   at org.apache.coyote.http11.InternalAprOutputBuffer.writeToSocket(InternalAprOutputBuffer.java:291)
solr_1  |   at org.apache.coyote.http11.InternalAprOutputBuffer.writeToSocket(InternalAprOutputBuffer.java:244)
solr_1  |   at org.apache.coyote.http11.InternalAprOutputBuffer.flushBuffer(InternalAprOutputBuffer.java:213)
solr_1  |   at org.apache.coyote.http11.InternalAprOutputBuffer.addToBB(InternalAprOutputBuffer.java:174)
solr_1  |   at org.apache.coyote.http11.InternalAprOutputBuffer.access$000(InternalAprOutputBuffer.java:40)
solr_1  |   at org.apache.coyote.http11.InternalAprOutputBuffer$SocketOutputBuffer.doWrite(InternalAprOutputBuffer.java:349)
solr_1  |   at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:118)
solr_1  |   at org.apache.coyote.http11.AbstractOutputBuffer.doWrite(AbstractOutputBuffer.java:256)
solr_1  |   at org.apache.coyote.Response.doWrite(Response.java:491)
solr_1  |   at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:391)
solr_1  |   ... 29 more
```

**Comment by xburda4** [comment]
to bolo moje hladanie dokumentov bez OCR, ospravedlňujem sa

**Comment by honza-rychtar** [comment]
SOLR nesmi spadnout, ani kdybych se ho snazil shodit.

**Comment by leiblix** [comment]
@xburda4 To nevadí, i takové dotazy by SOLR měl zvládat :-)

@honza-rychtar Souhlas

**Comment by LenkaKravecova** [comment]
Padání SOLRu řešíme. Toto byl konrkétní příklad, takže zavírám.
