### ISSUE TITLE
Chyba cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#144]
Chyba má 1,084 hitů za posledních 24 hodin

Požadavek na:

http://kramerius.mzk.cz/search/img?uuid=uuid:76d89cb0-877c-11e5-ac67-005056827e51&stream=IMG_THUMB&action=SCALE&scaledHeight=96

vyvolá vždy stacktrace:

```
kramerius_1  | 25-Oct-2016 12:30:06.986 SEVERE [http-nio-8080-exec-2] cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet protocol = http host = null
kramerius_1  |  java.lang.IllegalArgumentException: protocol = http host = null
kramerius_1  |  at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:176)
kramerius_1  |  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1099)
kramerius_1  |  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
kramerius_1  |  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
kramerius_1  |  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
kramerius_1  |  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
kramerius_1  |  at cz.incad.kramerius.impl.FedoraAccessImpl.getSmallThumbnail(FedoraAccessImpl.java:344)
kramerius_1  |  at cz.incad.kramerius.security.SecuredFedoraAccessImpl.getSmallThumbnail(SecuredFedoraAccessImpl.java:150)
kramerius_1  |  at cz.incad.kramerius.impl.fedora.FedoraURLConnection.getInputStream(FedoraURLConnection.java:38)
kramerius_1  |  at java.net.URL.openStream(URL.java:1045)
kramerius_1  |  at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:80)
kramerius_1  |  at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:52)
kramerius_1  |  at cz.incad.Kramerius.AbstractImageServlet.rawImage(AbstractImageServlet.java:149)
kramerius_1  |  at cz.incad.Kramerius.imaging.ImageStreamsServlet.access$500(ImageStreamsServlet.java:51)
kramerius_1  |  at cz.incad.Kramerius.imaging.ImageStreamsServlet$Actions$2.doPerform(ImageStreamsServlet.java:234)
kramerius_1  |  at cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet(ImageStreamsServlet.java:150)
kramerius_1  |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
kramerius_1  |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
kramerius_1  |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
kramerius_1  |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  |  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
kramerius_1  |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
kramerius_1  |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  |  at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
kramerius_1  |  at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
kramerius_1  |  at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
kramerius_1  |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
kramerius_1  |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  |  at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
kramerius_1  |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
kramerius_1  |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
kramerius_1  |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
kramerius_1  |  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
kramerius_1  |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
kramerius_1  |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
kramerius_1  |  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
kramerius_1  |  at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
kramerius_1  |  at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240)
kramerius_1  |  at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:569)
kramerius_1  |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
kramerius_1  |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
kramerius_1  |  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
kramerius_1  |  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
kramerius_1  |  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
kramerius_1  |  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
kramerius_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
kramerius_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
kramerius_1  |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
kramerius_1  |  at java.lang.Thread.run(Thread.java:745)
kramerius_1  | 
```

**Comment by leiblix** [comment]
U některých obrázků u NDK bylo http se 3 lomítky (chvíli byl špatně nakonfigurován TM modul). Data jsou už opravená a tato chyba se už v Kibaně nevyskytuje
