### ISSUE TITLE
Chyba cz.incad.kramerius.security.impl.criteria.BenevolentMovingWall.evaluateDoc unexpected char: '['

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#145]
Chyba má 5,919 hitů za posledních 24 hodin

Požadavek např. na:

http://kramerius.mzk.cz/search/i.jsp?pid=uuid:6cb65cd0-8a56-11e6-8aeb-5ef3fc9ae867

vyvolá vždy stacktrace:

```
kramerius_1  | 25-Oct-2016 12:55:36.587 SEVERE [http-nio-8080-exec-45] cz.incad.kramerius.security.impl.criteria.BenevolentMovingWall.evaluateDoc unexpected char: '['
kramerius_1  |  line 1:1: unexpected char: '['
kramerius_1  |  at cz.incad.kramerius.security.impl.criteria.mw.DateLexer.nextToken(DateLexer.java:97)
kramerius_1  |  at antlr.TokenBuffer.fill(TokenBuffer.java:69)
kramerius_1  |  at antlr.TokenBuffer.LA(TokenBuffer.java:80)
kramerius_1  |  at antlr.LLkParser.LA(LLkParser.java:52)
kramerius_1  |  at cz.incad.kramerius.security.impl.criteria.mw.DatesParser.dates(DatesParser.java:83)
kramerius_1  |  at cz.incad.kramerius.security.impl.criteria.BenevolentMovingWall.evaluateDoc(BenevolentMovingWall.java:110)
kramerius_1  |  at cz.incad.kramerius.security.impl.criteria.BenevolentMovingWall.resolveInternal(BenevolentMovingWall.java:95)
kramerius_1  |  at cz.incad.kramerius.security.impl.criteria.BenevolentMovingWall.evalute(BenevolentMovingWall.java:66)
kramerius_1  |  at cz.incad.kramerius.security.impl.RightImpl.evaluate(RightImpl.java:107)
kramerius_1  |  at cz.incad.kramerius.security.impl.DatabaseRightsManager.resolve(DatabaseRightsManager.java:250)
kramerius_1  |  at cz.incad.kramerius.security.impl.http.IsActionAllowedFromRequest.isAllowedInternalForFedoraDocuments(IsActionAllowedFromRequest.java:112)
kramerius_1  |  at cz.incad.kramerius.security.impl.http.IsActionAllowedFromRequest.isActionAllowed(IsActionAllowedFromRequest.java:71)
kramerius_1  |  at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source)
kramerius_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kramerius_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
kramerius_1  |  at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
kramerius_1  |  at com.sun.proxy.$Proxy74.isActionAllowed(Unknown Source)
kramerius_1  |  at cz.incad.kramerius.security.SecuredFedoraAccessImpl.getDataStream(SecuredFedoraAccessImpl.java:227)
kramerius_1  |  at cz.incad.Kramerius.views.inc.details.tabs.LoadCustomViewObject.getContent(LoadCustomViewObject.java:105)
kramerius_1  |  at sun.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
kramerius_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kramerius_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
kramerius_1  |  at javax.el.BeanELResolver.getValue(BeanELResolver.java:97)
kramerius_1  |  at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:110)
kramerius_1  |  at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
kramerius_1  |  at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
--
kramerius_1  |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
kramerius_1  |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
kramerius_1  |  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
kramerius_1  |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
kramerius_1  |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
kramerius_1  |  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
kramerius_1  |  at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
kramerius_1  |  at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240)
kramerius_1  |  at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:569)
kramerius_1  |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
kramerius_1  |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
kramerius_1  |  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
kramerius_1  |  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
kramerius_1  |  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
kramerius_1  |  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
kramerius_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
kramerius_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
kramerius_1  |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
kramerius_1  |  at java.lang.Thread.run(Thread.java:745)



```

**Comment by jkremlacek** [comment]
Chybuje to asi na více věcech.

Příklad v tomto issue kolabuje např. na elementu s rokem vydání který obsahuje "c2001", viz elementy mods:dateIssued, <dateIssued>.

Pokud metoda DateLexer:nextToken() dostane na vstupu bufferu jiný symbol než '-', '0' ... '9', '.', '\X' (X = {t, n, r}), ' ' automaticky vyhodí vyjímku. --- c2001 tedy taky vyhodí kvůli 'c'.

Proč je v stacktrace-u '[' nemám ponětí, na testovacím krameriovi vyhodí jen 2x 'c'.

**Comment by Jenyk** [comment]
To je v pořádku, prostě jsou tam formáty roku vydání, které pohyblivá zeď nebere. 
Problém je (byl, viz https://github.com/ceskaexpedice/kramerius/issues/461) ve způsobu logování, ne v konkrétním formátu roku.
Data už podle logů poopravujeme.

**Comment by Jenyk** [comment]
Druhá možnost je upravit pohyblivou zeď a nebo (lepší) používat skript od p. Šilhavého.

**Comment by leiblix** [comment]
Bylo vyřešeno https://github.com/ceskaexpedice/kramerius/issues/461
