### ISSUE TITLE
Read timeout při indexaci

### ISSUE THREAD

**Issue by Jenyk** [moravianlibrary/kramerius#153]
Solr poslední dobou zase často vrací 
 
`java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1323)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at cz.incad.kramerius.impl.FedoraAccessImpl.getDataStream(FedoraAccessImpl.java:907)
	at cz.incad.kramerius.relation.RelationUtils.getDataStream(RelationUtils.java:59)
	at cz.incad.kramerius.relation.RelationUtils.getRelsExt(RelationUtils.java:51)
	at cz.incad.kramerius.relation.impl.RelationServiceImpl.load(RelationServiceImpl.java:61)
	... 9 more
`

Z posledních 28 NDK procesů jich na tom spadlo 18. Projevuje se to na ostrém K5, na NDK i na infra.

**Comment by leiblix** [comment]
Solr? Celý stacktrace je o Fedoře, ne? :)

Toto je vidět přímo v procesech?

**Comment by Jenyk** [comment]
Asi máš pravdu. Je to vidět přímo v procesech v k5, příklad celého chybového logu:
https://gist.github.com/Jenyk/9c99f7949a2532f2175336d675b2e9e2

**Comment by Jenyk** [comment]
(Dočasně) pomáhá otočení fedory

**Comment by xburda4** [comment]
Mala by stačiť zmena hodnoty http.connection v configuration.properties. Funkcia, ktorá otvára URL spojenie používa metódu, ktorá v dokumentácii hovorí "If the timeout expires before the connection can be established, a java.net.SocketTimeoutException is raised". Konkrétne to sú https://github.com/ceskaexpedice/kramerius/blob/1c91829bc1f9c109964d7a6d6b57ef10fdfbb7ef/common/src/main/java/cz/incad/kramerius/utils/RESTHelper.java#L36-L37

Edit: Nepomohlo, dnes ráno mi na tom padali importy, resp. indexácie.

**Comment by xburda4** [comment]
K výskytu tejto chyby prispieva OCR na serveroch MZK. Pri vkladaní datastreamov sa fedora asi tak vyťaží, že na ostatné príkazy neodpovedá včas a vyskočí výnimka. Pri spustenom OCR na pražských serveroch som si túto chybu nevšimol.   

Tiež treba kontrolovať logy vo fedore. Ideálne každých pár dní mazať logy localhost_access_log.*, aby na servery nedošlo miesto, čo môže tiež robiť problémy.

**Comment by xburda4** [comment]
Na fedore je nastavenie, aby sa nezapisovali localhost_access_log-y. Miesto na fedore teda bude a chyba by mala byť odstránená. Pár dní to ešte budem sledovať a ak bude všetko v poriadku, issue uzavrem.

**Comment by xburda4** [comment]
Po prechode na nový Solr sa Read Timeout takmer nevyskytol. Zatváram issue.
