### ISSUE TITLE
Chybné zobrazování některých PDF v Krameriu

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#156]
Tato PDF po zpracování v Editoru nějak blbnou, ale myslím si, že je to chyba Krameria.

```
uuid:ffafcb50-6aaa-4919-a0a8-a88e54350f46
uuid:b635554d-8608-4b87-b241-0cbcade961c8
uuid:e9c8af19-344c-4613-a4cc-d35e6f891cdc
uuid:ef1389fe-8aee-4b39-944b-961b8a8f2da6
uuid:739f7813-c89d-40f6-a80c-a55c4beec411
uuid:999feaf1-2804-4bde-9e3b-249ba393dfb4
uuid:5324b206-a491-465e-b9e1-9570487c973f
uuid:7ad3024b-3f03-4416-9f31-1d5805f36005
```

Minimálně první uuid:ffafcb50-6aaa-4919-a0a8-a88e54350f46 se zdá být podle Fedory v pořádku, ale Kramerius vyhodí stacktrace:
```
12-Dec-2016 12:48:04.082 SEVERE [http-nio-8080-exec-10] cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet Unsupported Image Type
 javax.imageio.IIOException: Unsupported Image Type
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1068)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
	at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:83)
	at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:52)
	at cz.incad.Kramerius.AbstractImageServlet.rawImage(AbstractImageServlet.java:149)
	at cz.incad.Kramerius.imaging.ImageStreamsServlet.access$500(ImageStreamsServlet.java:51)
	at cz.incad.Kramerius.imaging.ImageStreamsServlet$Actions$2.doPerform(ImageStreamsServlet.java:234)
	at cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet(ImageStreamsServlet.java:150)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:291)
	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:569)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

pozn. chyba se dá zreplikovat i na čisté instalaci

**Comment by jkremlacek** [comment]
Chyba je v načítání thumbnail-u, kdy `javax.imageio.ImageIO` při zavolání `read` vyhodí zmíněnou chybu: `at javax.imageio.ImageIO.read(ImageIO.java:1448)`.

Segment kódu pro testování: https://codeshare.io/5Xgj82

Chyba je v kódování barev v CMYK viz: http://stackoverflow.com/questions/7177655/java-imageio-iioexception-unsupported-image-type

**Comment by leiblix** [comment]
Závěr: náhledy Krameria musí být vždy RGB, bude nutné upravit editor
