### ISSUE TITLE
Dokument je v indexu, ale ve Fedoře chybí

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#175]
http://kramerius.mzk.cz/search/i.jsp?pid=uuid:7895b070-2e55-11e2-a1eb-5ef3fc9bb22f

dotaz do SOLru http://solr.dk-back.infra.mzk.cz/solr/kramerius/select/?q=PID%3Auuid%5C%3A7895b070-2e55-11e2-a1eb-5ef3fc9bb22f&version=2.2&start=0&rows=10&indent=on

**Comment by xburda4** [comment]
Súvisí s https://github.com/moravianlibrary/kramerius/issues/73, čakáme na reimport z LTP.

**Comment by leiblix** [comment]
Než se to provede, tak bychom takové dokumenty měly smazat z indexu. Každý reqeust do logu vloží takovýto balast:


```
kramerius_1  | 10-Apr-2017 13:00:13.196 SEVERE [http-nio-8080-exec-83] cz.incad.kramerius.utils.RESTHelper.inputStream status code 404
kramerius_1  | 10-Apr-2017 13:00:13.196 SEVERE [http-nio-8080-exec-83] cz.incad.kramerius.utils.RESTHelper.inputStream 
kramerius_1  | 
kramerius_1  | 
kramerius_1  | 
kramerius_1  | 
kramerius_1  | 
kramerius_1  | <html><head>
kramerius_1  |       <title>Fedora: 404 Not Found</title></head>
kramerius_1  |    <body>
kramerius_1  |       <center>
kramerius_1  |          <table border="0" cellpadding="0" cellspacing="0" width="784">
kramerius_1  |             <tbody><tr>
kramerius_1  | 				<td height="134" valign="top" width="141"><img src="/fedora/images/newlogo2.jpg" height="134" width="141"></td>
kramerius_1  |                <td valign="top" width="643">
kramerius_1  |                   <center>
kramerius_1  |                      <h2>404 Not Found</h2>
kramerius_1  |                      <h3>No such object, datastream, or dissemination.</h3>
kramerius_1  |                   </center>
kramerius_1  | no path in db registry for [uuid:7895b070-2e55-11e2-a1eb-5ef3fc9bb22f]
kramerius_1  |                </td>
kramerius_1  |             </tr>
kramerius_1  |          </tbody></table>
kramerius_1  |       </center>
kramerius_1  |    </body></html>
kramerius_1  | 
kramerius_1  | 10-Apr-2017 13:00:13.199 SEVERE [http-nio-8080-exec-83] cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter An exception occurred processing JSP page /inc/html_header.jsp at line 62
kramerius_1  | 
kramerius_1  | 59:         <meta property="og:site_name" content="${fb.applicationTitle}"/>
kramerius_1  | 60: 
kramerius_1  | 61:         <meta property="og:description"
kramerius_1  | 62:               content="${fb.description}"/>
kramerius_1  | 63:               
kramerius_1  | 64:         <link rel="canonical" href="${fb.shareURL}" />
kramerius_1  | 65:     </c:if>
kramerius_1  | 
kramerius_1  | 
kramerius_1  | Stacktrace:
kramerius_1  |  org.apache.jasper.JasperException: An exception occurred processing JSP page /inc/html_header.jsp at line 62
kramerius_1  | 
kramerius_1  | 59:         <meta property="og:site_name" content="${fb.applicationTitle}"/>
kramerius_1  | 60: 
kramerius_1  | 61:         <meta property="og:description"
kramerius_1  | 62:               content="${fb.description}"/>
kramerius_1  | 63:               
kramerius_1  | 64:         <link rel="canonical" href="${fb.shareURL}" />
kramerius_1  | 65:     </c:if>
kramerius_1  | 
kramerius_1  | 
kramerius_1  | Stacktrace:
kramerius_1  | 	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:579)
kramerius_1  | 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
kramerius_1  | 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
kramerius_1  | 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
kramerius_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
kramerius_1  | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
kramerius_1  | 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  | 	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
kramerius_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
kramerius_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
kramerius_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
kramerius_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
kramerius_1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
kramerius_1  | 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
kramerius_1  | 	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240)
kramerius_1  | 	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:569)
kramerius_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
kramerius_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
kramerius_1  | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
kramerius_1  | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
kramerius_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
kramerius_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
kramerius_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
kramerius_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
kramerius_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
kramerius_1  | 	at java.lang.Thread.run(Thread.java:745)
kramerius_1  | Caused by: javax.el.ELException: Error reading 'description' on type cz.incad.Kramerius.views.social.FacebookLikeItButton
kramerius_1  | 	at javax.el.BeanELResolver.getValue(BeanELResolver.java:101)
kramerius_1  | 	at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:110)
kramerius_1  | 	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
kramerius_1  | 	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
kramerius_1  | 	at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:943)
kramerius_1  | 	at org.apache.jsp.i_jsp._jspx_meth_c_005fif_005f2(i_jsp.java:4640)
kramerius_1  | 	at org.apache.jsp.i_jsp._jspService(i_jsp.java:365)
kramerius_1  | 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
kramerius_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
kramerius_1  | 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
kramerius_1  | 	... 35 more
kramerius_1  | Caused by: java.io.FileNotFoundException: http://fedora.dk-back.infra.mzk.cz/fedora/get/uuid:7895b070-2e55-11e2-a1eb-5ef3fc9bb22f/DC
kramerius_1  | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
kramerius_1  | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
kramerius_1  | 	at cz.incad.kramerius.utils.RESTHelper.inputStream(RESTHelper.java:38)
kramerius_1  | 	at cz.incad.kramerius.impl.FedoraAccessImpl.getDC(FedoraAccessImpl.java:216)
kramerius_1  | 	at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
kramerius_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kramerius_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
kramerius_1  | 	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
kramerius_1  | 	at com.sun.proxy.$Proxy75.getDC(Unknown Source)
kramerius_1  | 	at cz.incad.kramerius.security.SecuredFedoraAccessImpl.getDC(SecuredFedoraAccessImpl.java:78)
kramerius_1  | 	at cz.incad.Kramerius.views.social.AbstractSocialButton.getDCDocument(AbstractSocialButton.java:207)
kramerius_1  | 	at cz.incad.Kramerius.views.social.AbstractSocialButton.getDescriptionForItem(AbstractSocialButton.java:214)
kramerius_1  | 	at cz.incad.Kramerius.views.social.AbstractSocialButton.getDescription(AbstractSocialButton.java:190)
kramerius_1  | 	at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
kramerius_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kramerius_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
kramerius_1  | 	at javax.el.BeanELResolver.getValue(BeanELResolver.java:97)
kramerius_1  | 	... 44 more
kramerius_1  | 
```

**Comment by xburda4** [comment]
To by sa mohlo vyriešiť v priebehu #83, teraz to reindexujem bez mazania, takže to nezmizne, ale tie menšie periodiká by som kludne mohol aj s mazaním, tie väčšie by som teda reindexoval po ročníkoch(?) alebo by som teda tie väčšie reindexoval ako dozeraz bez mazania.

**Comment by xburda4** [comment]
Musel som z foxml vymyzať záznam o uuid:7895b070-2e55-11e2-a1eb-5ef3fc9bb22f, ktorý teda nemáme nikde a čakáme na jeho import z LTP. Momentálne sa to reindexuje a táto chyba by už vyskakovať nemala.
