### ISSUE TITLE
Reindexácie z meditoru padajú

### ISSUE THREAD

**Issue by xburda4** [moravianlibrary/kramerius#176]
Niektoré reindexácie z meditoru spadli na nejakej chybe so Solrom. Bude to asi len nejaká chyba pri adrese alebo niečo podobné. 

SEVERE: Cant index. Action:fromKrameriusModel Value: uuid:b390ae9f-79f9-4761-9bf1-091c375d7d20
java.lang.Exception: java.lang.Exception: Solr has throw an error. Check tomcat log. java.io.IOException: Server returned HTTP response code: 400 for URL: http://solr.dk-back.infra.mzk.cz/solr/kramerius/update
	at cz.incad.kramerius.indexer.SolrOperations.indexByPid(SolrOperations.java:490)
	at cz.incad.kramerius.indexer.SolrOperations.fromKrameriusModel(SolrOperations.java:365)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:120)
	at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:51)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:118)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:112)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:103)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:76)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by xburda4** [comment]
Vyzerá to tak, že Jetty(9.3.8) na ktorom beží Solr má nejaké problémy s requestom z krameria, na ktorom to následne padne. Na solri vyskočilo "bad HTTP parsed: 400 Unknown Version for HttpChannelOverHttp@79d95bfa{r=5,&#8203;c=false,&#8203;a=IDLE,&#8203;uri=null}", tak predpokladám, že to s tým súvisí.
