### ISSUE TITLE
Generování PDF vyhazuje stacktrace

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#202]
Např.: http://kramerius.mzk.cz/search/handle/uuid:90a15480-f782-11e6-8830-005056827e51

```
kramerius_1  | 11-Aug-2017 08:28:19.692 SEVERE [http-nio-8080-exec-1619] cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter null
kramerius_1  |  cz.knav.pdf.PdfTextUnderImageException
kramerius_1  | 	at cz.knav.pdf.PdfTextUnderImage.throwPdfTextUnderImageException(PdfTextUnderImage.java:301)
kramerius_1  | 	at cz.knav.pdf.PdfTextUnderImage.getFontFamily(PdfTextUnderImage.java:137)
kramerius_1  | 	at cz.knav.pdf.PdfTextUnderImage.putTextsToPdf(PdfTextUnderImage.java:109)
kramerius_1  | 	at cz.knav.pdf.PdfTextUnderImage.imageWithAlto(PdfTextUnderImage.java:82)
kramerius_1  | 	at cz.incad.kramerius.pdf.commands.render.RenderPDF$Processor.create(RenderPDF.java:382)
kramerius_1  | 	at cz.incad.kramerius.pdf.commands.render.RenderPDF$Processor.before(RenderPDF.java:217)
kramerius_1  | 	at cz.incad.kramerius.pdf.commands.Image.process(Image.java:53)
kramerius_1  | 	at cz.incad.kramerius.pdf.commands.ITextCommands.process(ITextCommands.java:89)
kramerius_1  | 	at cz.incad.kramerius.pdf.commands.render.RenderPDF.render(RenderPDF.java:89)
kramerius_1  | 	at cz.incad.kramerius.pdf.impl.SimplePDFServiceImpl.pdf(SimplePDFServiceImpl.java:103)
kramerius_1  | 	at cz.incad.kramerius.rest.api.k5.client.pdf.AbstractPDFResource.selection(AbstractPDFResource.java:177)
kramerius_1  | 	at cz.incad.kramerius.rest.api.k5.client.pdf.PDFResource.selection(PDFResource.java:274)
kramerius_1  | 	at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
kramerius_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kramerius_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
kramerius_1  | 	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
kramerius_1  | 	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
kramerius_1  | 	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
kramerius_1  | 	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
kramerius_1  | 	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
kramerius_1  | 	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
kramerius_1  | 	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
kramerius_1  | 	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
kramerius_1  | 	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
kramerius_1  | 	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
kramerius_1  | 	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
kramerius_1  | 	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
kramerius_1  | 	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
kramerius_1  | 	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
kramerius_1  | 	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
kramerius_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
kramerius_1  | 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
kramerius_1  | 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
kramerius_1  | 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
kramerius_1  | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
kramerius_1  | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
kramerius_1  | 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  | 	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  | 	at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:26)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  | 	at cz.incad.kramerius.auth.basic.AuthFilter.basicAuth(AuthFilter.java:123)
kramerius_1  | 	at cz.incad.kramerius.auth.basic.AuthFilter.doFilter(AuthFilter.java:87)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  | 	at cz.incad.Kramerius.ClientClosedRequestFilter.doFilter(ClientClosedRequestFilter.java:25)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
kramerius_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
kramerius_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
kramerius_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
kramerius_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
kramerius_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
kramerius_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
kramerius_1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
kramerius_1  | 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
kramerius_1  | 	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240)
kramerius_1  | 	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:569)
kramerius_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
kramerius_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
kramerius_1  | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
kramerius_1  | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
kramerius_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
kramerius_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
kramerius_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
kramerius_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
kramerius_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
kramerius_1  | 	at java.lang.Thread.run(Thread.java:748)
kramerius_1  | 
```

**Comment by MarosGrm** [comment]
Generovanie PDF už stacktrace nevyhadzuje.
