### ISSUE TITLE
Stacktrace - chybejici OCR

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#224]
URL http://kramerius.mzk.cz/search/img?uuid=uuid:12b42738-9844-4a77-895c-d77b2bc89a72&stream=TEXT_OCR&action=GETRAW
(dokument neobsahujici OCR), vraci tento osklivy stacktrace. Misto toho nahradit kratkou hlaskou, ze ten datastream chybi.
```
kramerius_1  | 07-Nov-2017 22:23:31.956 SEVERE [http-nio-8080-exec-930] cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet null
kramerius_1  |  cz.incad.kramerius.FedoraIOException
kramerius_1  | 	at cz.incad.kramerius.impl.FedoraAccessImpl.getStreamProfile(FedoraAccessImpl.java:1090)
kramerius_1  | 	at cz.incad.kramerius.impl.FedoraAccessImpl.referencedDataStream(FedoraAccessImpl.java:955)
kramerius_1  | 	at cz.incad.kramerius.impl.FedoraAccessImpl.getDataStream(FedoraAccessImpl.java:931)
kramerius_1  | 	at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
kramerius_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kramerius_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
kramerius_1  | 	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
```

Podle Kibany to ma za minuly tyden 1865 hitu

**Comment by kazooo** [comment]
Týká se to jenom OCR datastreamu? Na jakou úrovni je to třeba logovat?

**Comment by leiblix** [comment]
Teoreticky se to může týkat jakéhokoliv datastreamu. Logoval bych to jako WARNING.

**Comment by leiblix** [comment]
Diky za vyreseni, ale prosim nezavirej mi to :) Ja si to zavru sam, az to mergnu do hlavni vetve (na ceskaexpedice), jinak bych na to mohl zapomenout.
