### ISSUE TITLE
Editor částí - nejde otevřit na lokálu

### ISSUE THREAD

**Issue by kazooo** [moravianlibrary/kramerius#245]
Logy:
```
02-Feb-2018 10:57:12.220 SEVERE [http-nio-8080-exec-6] cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.execute null
 java.io.IOException: Cannot load relations: ...
	at cz.incad.kramerius.relation.impl.RelationServiceImpl.load(RelationServiceImpl.java:64)
	at cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.fetchRelations(GetKrameriusObjectQueryHandler.java:161)
...
```

**Comment by kazooo** [comment]
Editor načítá adresu Fedory jako http://localhost:8080 ale měla by to byt adresa docker kontejneru, (http://fcrepo:8080), proto editor nemůže načíst objekt z Fedory.

Kvůli tomu že editor požívá staré knihovny Krameria (*common*, *fedora-api*, *security-core*), chybí mu nekteré věci, jako např. načtení proměnnych prostředí do KConfiguration, který editor volá všude. Aktualizace knihoven editora řeší toto issue a #237.

**Comment by kazooo** [comment]
Opravený editor částí je v novém releasu [Krameria 5.4.2](https://github.com/ceskaexpedice/kramerius/releases/tag/5.4.2)
