### ISSUE TITLE
Testování virtuální sbírky

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#28]
Zařadit test endpointu http://kramerius.mzk.cz/search/api/v5.0/vc/ do zátěžových testů v repozitáři https://github.com/moravianlibrary/kramerius-performance-test

**Comment by leiblix** [comment]
na krameriustest.mzk.cz nejde vůbec virtuální sbírka přidat

14-Sep-2015 14:36:09.438 SEVERE [http-nio-8080-exec-138] null.null  Caused by: [DefaultExternalContentManager] returned an error.  The underlying error was a org.fcrepo.server.errors.GeneralException  The message was  "Error getting http://krameriustest.mzk.cz/search/vc?action=TEXT&content=test"  .  
 javax.xml.ws.soap.SOAPFaultException:  Caused by: [DefaultExternalContentManager] returned an error.  The underlying error was a org.fcrepo.server.errors.GeneralException  The message was  "Error getting http://krameriustest.mzk.cz/search/vc?action=TEXT&content=test"  .  
    at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
    at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:122)
    at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
    at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
    at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
    at com.sun.proxy.$Proxy675.addDatastream(Unknown Source)
    at cz.incad.kramerius.virtualcollections.VirtualCollectionsManager.modifyDatastream(VirtualCollectionsManager.java:393)
    at cz.incad.Kramerius.views.virtualcollection.VirtualCollectionServlet$Actions$7.doPerform(VirtualCollectionServlet.java:246)
    at cz.incad.Kramerius.views.virtualcollection.VirtualCollectionServlet.doGet(VirtualCollectionServlet.java:48)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
    at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:291)
    at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:481)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

**Comment by leiblix** [comment]
zařazeno do zátěžových testů
