### ISSUE TITLE
Špatné obrazové datastreamy

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#42]
Náhodou jsem při procházení Tomcat logu našel chybu

```
SEVERE: Server returned HTTP response code: 400 for URL: http://ndk-test.mzk.cz/imageserver/NDK/2013/be2b2490-24c2-11e2-8579-005056827e52/1_10009216990001.tif/thumb.jpg
java.io.IOException: Server returned HTTP response code: 400 for URL: http://ndk-test.mzk.cz/imageserver/NDK/2013/be2b2490-24c2-11e2-8579-005056827e52/1_10009216990001.tif/thumb.jpg
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
    at cz.incad.kramerius.impl.FedoraAccessImpl.getSmallThumbnail(FedoraAccessImpl.java:344)
    at cz.incad.kramerius.security.SecuredFedoraAccessImpl.getSmallThumbnail(SecuredFedoraAccessImpl.java:150)
    at cz.incad.kramerius.impl.fedora.FedoraURLConnection.getInputStream(FedoraURLConnection.java:38)
    at java.net.URL.openStream(URL.java:1037)
    at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:71)
    at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:49)
    at cz.incad.Kramerius.AbstractImageServlet.rawImage(AbstractImageServlet.java:156)
    at cz.incad.Kramerius.imaging.ImageStreamsServlet.access$500(ImageStreamsServlet.java:56)
    at cz.incad.Kramerius.imaging.ImageStreamsServlet$Actions$2.doPerform(ImageStreamsServlet.java:239)
    at cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet(ImageStreamsServlet.java:155)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
    at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:309)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
```

jedná se o dokument http://krameriusndktest.mzk.cz/search/i.jsp?pid=uuid:be2b2490-24c2-11e2-8579-005056827e52

Jak se to dostalo do ostrého Krameria a kolik tam takových zmetků je?

**Comment by zabak** [comment]
V NK stejná věc obrázky má. Určitě to není výjimka, tj. měla by se udělat celková kontrola našeho Krameria :-(

**Comment by LenkaKravecova** [comment]
@xermak00 @kenji1322 @hlavacekrene, můžete se na to někdo podívat, jestli je to stále aktuální? Ten odkazovaný dokument se zdá být v pořádku. Díky.

**Comment by MarosGrm** [comment]
Obrázky sú v poriadku. Ich počet na IS sedí s počtom stránok. Celková kontrola Krameria by sa určite niekedy v budúcnosti mohla spraviť.
