### ISSUE TITLE
SEVERE chyby v logu s moving wall

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#44]
V logu se teď poměrně často vyskytuje chyba

```
INFO: [] webapp=/solr path=/select params={q=PID:"uuid:ed291865-d2fc-4e68-99e6-6b100d9c5127"} hits=1 status=0 QTime=0 
X 19, 2015 8:56:13 DOP. cz.incad.kramerius.security.impl.criteria.BenevolentMovingWall evaluateDoc
SEVERE: unexpected char: 'm'
line 1:1: unexpected char: 'm'
    at cz.incad.kramerius.security.impl.criteria.mw.DateLexer.nextToken(DateLexer.java:97)
    at antlr.TokenBuffer.fill(TokenBuffer.java:69)
    at antlr.TokenBuffer.LA(TokenBuffer.java:80)
    at antlr.LLkParser.LA(LLkParser.java:52)
    at cz.incad.kramerius.security.impl.criteria.mw.DatesParser.dates(DatesParser.java:83)
    at cz.incad.kramerius.security.impl.criteria.BenevolentMovingWall.evaluateDoc(BenevolentMovingWall.java:110)
    at cz.incad.kramerius.security.impl.criteria.BenevolentMovingWall.resolveInternal(BenevolentMovingWall.java:95)
    at cz.incad.kramerius.security.impl.criteria.BenevolentMovingWall.evalute(BenevolentMovingWall.java:66)
    at cz.incad.kramerius.security.impl.RightImpl.evaluate(RightImpl.java:107)
    at cz.incad.kramerius.security.impl.DatabaseRightsManager.resolve(DatabaseRightsManager.java:250)
    at cz.incad.kramerius.security.impl.http.IsActionAllowedFromRequest.isAllowedInternalForFedoraDocuments(IsActionAllowedFromRequest.java:150)
    at cz.incad.kramerius.security.impl.http.IsActionAllowedFromRequest.isActionAllowed(IsActionAllowedFromRequest.java:97)
    at cz.incad.Kramerius.imaging.ZoomifyServlet.doGet(ZoomifyServlet.java:121)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:26)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:589)
    at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:394)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:291)
    at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
    at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
    at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
    at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
    at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by Jenyk** [comment]
V MODS je tag: `<dateIssued>mezi 1829 a 1833]</dateIssued>`

**Comment by leiblix** [comment]
Seznam http://kramerius.mzk.cz/search/api/v5.0/search?q=datum_str:mezi*

**Comment by Jenyk** [comment]
Povel: změnit data na rok-rok
