### ISSUE TITLE
Rebuild Fedory MZK

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#51]
Rebuild  fedora.mzk.cz padne na následující hlášce (nutné dořešit před spojením Fedor):

```
ERROR 12:00:22.147 (DBPathRegistry) ending rebuild unsuccessfully
org.fcrepo.server.errors.LowlevelStorageException: PID delimiter (:) is missing.    PID delimiter (:) is missing.
    at org.fcrepo.server.storage.lowlevel.PathAlgorithm.decode(PathAlgorithm.java:50) ~[fcrepo-server-3.8.0.jar:na]
    at org.fcrepo.server.storage.lowlevel.PathRegistry.traverseFiles(PathRegistry.java:115) ~[fcrepo-server-3.8.0.jar:na]
    at org.fcrepo.server.storage.lowlevel.PathRegistry.traverseFiles(PathRegistry.java:95) ~[fcrepo-server-3.8.0.jar:na]
    at org.fcrepo.server.storage.lowlevel.PathRegistry.traverseFiles(PathRegistry.java:183) ~[fcrepo-server-3.8.0.jar:na]
    at org.fcrepo.server.storage.lowlevel.DBPathRegistry.rebuild(DBPathRegistry.java:277) ~[fcrepo-server-3.8.0.jar:na]
    at org.fcrepo.server.storage.lowlevel.defaultstore.Store.rebuild(Store.java:96) [fcrepo-server-3.8.0.jar:na]
    at org.fcrepo.server.storage.lowlevel.DefaultLowlevelStorage.rebuildObject(DefaultLowlevelStorage.java:97) [fcrepo-server-3.8.0.jar:na]
    at org.fcrepo.server.storage.lowlevel.DefaultLowlevelStorageModule.rebuildObject(DefaultLowlevelStorageModule.java:141) [fcrepo-server-3.8.0.jar:na]
    at org.fcrepo.server.utilities.rebuild.SQLRebuilder.start(SQLRebuilder.java:161) [fcrepo-server-3.8.0.jar:na]
    at org.fcrepo.server.utilities.rebuild.Rebuild.run(Rebuild.java:118) [fcrepo-server-3.8.0.jar:na]
    at org.fcrepo.server.utilities.rebuild.Rebuild.main(Rebuild.java:467) [fcrepo-server-3.8.0.jar:na]
Caused by: org.fcrepo.server.errors.MalformedPidException: PID delimiter (:) is missing.
    at org.fcrepo.server.Server.pidFromFilename(Server.java:1511) ~[fcrepo-server-3.8.0.jar:na]
    at org.fcrepo.server.storage.lowlevel.PathAlgorithm.decode(PathAlgorithm.java:47) ~[fcrepo-server-3.8.0.jar:na]
    ... 10 common frames omitted
org.fcrepo.server.errors.LowlevelStorageException: ending rebuild unsuccessfully    PID delimiter (:) is missing.PID delimiter (:) is missing.
    at org.fcrepo.server.storage.lowlevel.DBPathRegistry.rebuild(DBPathRegistry.java:283)
    at org.fcrepo.server.storage.lowlevel.defaultstore.Store.rebuild(Store.java:96)
    at org.fcrepo.server.storage.lowlevel.DefaultLowlevelStorage.rebuildObject(DefaultLowlevelStorage.java:97)
    at org.fcrepo.server.storage.lowlevel.DefaultLowlevelStorageModule.rebuildObject(DefaultLowlevelStorageModule.java:141)
    at org.fcrepo.server.utilities.rebuild.SQLRebuilder.start(SQLRebuilder.java:161)
    at org.fcrepo.server.utilities.rebuild.Rebuild.run(Rebuild.java:118)
    at org.fcrepo.server.utilities.rebuild.Rebuild.main(Rebuild.java:467)
Caused by: org.fcrepo.server.errors.LowlevelStorageException: PID delimiter (:) is missing. PID delimiter (:) is missing.
    at org.fcrepo.server.storage.lowlevel.PathAlgorithm.decode(PathAlgorithm.java:50)
    at org.fcrepo.server.storage.lowlevel.PathRegistry.traverseFiles(PathRegistry.java:115)
    at org.fcrepo.server.storage.lowlevel.PathRegistry.traverseFiles(PathRegistry.java:95)
    at org.fcrepo.server.storage.lowlevel.PathRegistry.traverseFiles(PathRegistry.java:183)
    at org.fcrepo.server.storage.lowlevel.DBPathRegistry.rebuild(DBPathRegistry.java:277)
    ... 6 more
Caused by: org.fcrepo.server.errors.MalformedPidException: PID delimiter (:) is missing.
    at org.fcrepo.server.Server.pidFromFilename(Server.java:1511)
    at org.fcrepo.server.storage.lowlevel.PathAlgorithm.decode(PathAlgorithm.java:47)
    ... 10 more
Error: Could not initialize class org.postgresql.util.PSQLException

java.lang.NoClassDefFoundError: Could not initialize class org.postgresql.util.PSQLException
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:286)
    at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
    at org.apache.commons.dbcp.PoolableConnectionFactory.validateConnection(PoolableConnectionFactory.java:658)
    at org.apache.commons.dbcp.PoolableConnectionFactory.validateObject(PoolableConnectionFactory.java:635)
    at org.apache.commons.pool.impl.GenericObjectPool.addObjectToPool(GenericObjectPool.java:1427)
    at org.apache.commons.pool.impl.GenericObjectPool.returnObject(GenericObjectPool.java:1393)
    at org.apache.commons.dbcp.PoolableConnection.close(PoolableConnection.java:90)
    at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.close(PoolingDataSource.java:191)
    at org.fcrepo.server.storage.ConnectionPool.free(ConnectionPool.java:337)
    at org.fcrepo.server.utilities.rebuild.SQLRebuilder.executeStatusSql(SQLRebuilder.java:203)
    at org.fcrepo.server.utilities.rebuild.SQLRebuilder.finishStatus(SQLRebuilder.java:181)
    at org.fcrepo.server.utilities.rebuild.SQLRebuilder.finish(SQLRebuilder.java:516)
    at org.fcrepo.server.utilities.rebuild.Rebuild.run(Rebuild.java:154)
    at org.fcrepo.server.utilities.rebuild.Rebuild.main(Rebuild.java:467)
```

**Comment by leiblix** [comment]
Postup puštění rebuildu Fedory

```
cd /docker-compose/fedoramzktest.mzk.cz/
docker-compose ps
```

To vypíše:

```
                 Name                               Command               State            Ports          
---------------------------------------------------------------------------------------------------------
fedoramzktestmzkcz_fcrepo_1              /docker-entrypoint.sh slee ...   Up      0.0.0.0:32774->8080/tcp 
fedoramzktestmzkcz_fedoraPostgres_1      /docker-entrypoint.sh postgres   Up      5432/tcp                
fedoramzktestmzkcz_riTriplesPostgres_1   /docker-entrypoint.sh postgres   Up      5432/tcp
```

Chceš jít do Fedory, takže si dej exec na ni

```
docker exec -it fedoramzktestmzkcz_fcrepo_1 bash
```

Uvnitř Fedory spusť skript rebuild.sh, vyber druhou možnost 2) Rebuild SQL database.

```
/usr/local/fedora/server/bin/fedora-rebuild.sh
```

Ten proces trvá hodně dlouho, tak je možné si od něj udělat disown (výsledek bude podobný nohup)

```
ctrl-z - pozastavíš proces
bg - hodíš ho do pozadí
disown %1 - odpojíš se
```

Nyní rebuild běží a můžeš se od kontejneru odpojit.

Sledovat postup lze tak, že se připojíš do kontejneru s postgres, tam se logneš jako postgres, dáš psql fedora3  a sleduješ přibývající data v tabulkách (prvně se dělá objectpaths).

Bohužel tím, že uděláš disown se připravíš o výstup toho skriptu, nevím teď jak to udělat jinak. Já si to prostě nechal jeden den běžet v konzoli a dával jsem si pozor na to, abych to nezavřel. Rebuildlo se cca 3 miliony objektů a potom to spadlo na chybě popsané v issue.

**Comment by Jenyk** [comment]
Pravděpodobně tomu vadí soubory objects/object.size a/nebo datastreams/md5_2010 a datastreams/md5_2011

Zkusím je smazat s rebuild znova spustit
