### ISSUE TITLE
Padá replikace dokumentů

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#79]
Padá replikace dokumentů... po čase při získávání FOXML to spadne na chybě 500.

Feb 20, 2016 12:04:47 PM org.kramerius.replications.K4ReplicationProcess phaseFailed
INFO: PHASE &#039;org.kramerius.replications.SecondPhase&#039; completed
Feb 20, 2016 12:04:47 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:118)
Caused by: java.lang.RuntimeException: org.kramerius.replications.PhaseException: com.sun.jersey.api.client.UniformInterfaceException: GET http://kramerius-new.mzk.cz/search/api/v4.6/replication/uuid:af8e6d80-91b2-11e3-b4dc-5ef3fc9ae867/foxml returned a response status of 500 Internal Server Error
    at org.kramerius.replications.K4ReplicationProcess.start(K4ReplicationProcess.java:134)
    at org.kramerius.replications.K4ReplicationProcess.replications(K4ReplicationProcess.java:81)
    ... 5 more
Caused by: org.kramerius.replications.PhaseException: com.sun.jersey.api.client.UniformInterfaceException: GET http://kramerius-new.mzk.cz/search/api/v4.6/replication/uuid:af8e6d80-91b2-11e3-b4dc-5ef3fc9ae867/foxml returned a response status of 500 Internal Server Error
    at org.kramerius.replications.SecondPhase.pidEmitted(SecondPhase.java:74)
    at org.kramerius.replications.SecondPhase$Emitter.pidEmitted(SecondPhase.java:274)
    at org.kramerius.replications.pidlist.PIDsListParser.rest(PIDsListParser.java:77)
    at org.kramerius.replications.pidlist.PIDsListParser.arrayVals(PIDsListParser.java:246)
    at org.kramerius.replications.pidlist.PIDsListParser.arrayDef(PIDsListParser.java:198)
    at org.kramerius.replications.pidlist.PIDsListParser.itemDef(PIDsListParser.java:137)
    at org.kramerius.replications.pidlist.PIDsListParser.pids(PIDsListParser.java:111)
    at org.kramerius.replications.SecondPhase.processIterate(SecondPhase.java:161)
    at org.kramerius.replications.SecondPhase.start(SecondPhase.java:50)
    at org.kramerius.replications.K4ReplicationProcess.start(K4ReplicationProcess.java:127)
    ... 6 more
Caused by: com.sun.jersey.api.client.UniformInterfaceException: GET http://kramerius-new.mzk.cz/search/api/v4.6/replication/uuid:af8e6d80-91b2-11e3-b4dc-5ef3fc9ae867/foxml returned a response status of 500 Internal Server Error
    at com.sun.jersey.api.client.WebResource.handle(WebResource.java:686)
    at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
    at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:507)
    at org.kramerius.replications.SecondPhase.rawFOXMLData(SecondPhase.java:128)
    at org.kramerius.replications.SecondPhase.pidEmitted(SecondPhase.java:61)
    ... 15 more

**Comment by leiblix** [comment]
Chyba reverzní proxy (malý timeout). Timeout jsme myslím zvedali a stejně se kramerius-new.mzk.cz teď nepoužívá.
